#ifndef MESSAGES_HPP
#define MESSAGES_HPP

namespace PyRiteMessages {

    // --- 一般的な値と操作のエラー ---
    constexpr const char* ERROR_UNSUPPORTED_OPERAND_ADD = "演算子 '+' にはサポートされていないオペランド型です。";
    constexpr const char* ERROR_UNSUPPORTED_OPERAND_SUB = "演算子 '-' にはサポートされていないオペランド型です。";
    constexpr const char* ERROR_UNSUPPORTED_OPERAND_MUL = "演算子 '*' にはサポートされていないオペランド型です。";
    constexpr const char* ERROR_UNSUPPORTED_OPERAND_DIV = "演算子 '/' にはサポートされていないオペランド型です。";
    constexpr const char* ERROR_UNSUPPORTED_OPERAND_POW = "演算子 '^' にはサポートされていないオペランド型です。";
    constexpr const char* ERROR_UNSUPPORTED_COMPARISON = "比較にはサポートされていないオペランド型です。";
    constexpr const char* ERROR_OBJECT_NOT_SUBSCRIPTABLE = "オブジェクトは添字アクセスできません。";
    constexpr const char* ERROR_OBJECT_ITEM_ASSIGNMENT_UNSUPPORTED = "オブジェクトは要素の代入をサポートしていません。";
    constexpr const char* ERROR_LIST_REPEAT_COUNT_INTEGER = "リストの繰り返し回数は整数でなければなりません。";
    constexpr const char* ERROR_LIST_INDEX_MUST_BE_NUMBER = "リストのインデックスは数値でなければなりません。";
    constexpr const char* ERROR_LIST_INDEX_OUT_OF_RANGE = "リストのインデックスが範囲外です。";
    constexpr const char* ERROR_INVALID_LIST_INDEX = "無効なリストのインデックスです。";
    constexpr const char* ERROR_HEX_STRING_PREFIX = "16進数文字列は '0x' で始まる必要があります。";

    // --- ランタイムとインタプリタのエラー ---
    constexpr const char* RUNTIME_ERROR_PREFIX = "[ランタイムエラー] 行 ";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_VARIABLE_PREFIX = "未定義の変数 '";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_VARIABLE_SUFFIX = "'。";
    constexpr const char* RUNTIME_ERROR_UNCAUGHT_EXCEPTION_PREFIX = "[未補足の例外] ";
    constexpr const char* RUNTIME_ERROR_STACK_TRACE_HEADER = "スタックトレース:";
    constexpr const char* RUNTIME_ERROR_STACK_TRACE_ENTRY_PREFIX = "  in ";
    constexpr const char* RUNTIME_ERROR_STACK_TRACE_ENTRY_SUFFIX = " (行 ";
    constexpr const char* RUNTIME_ERROR_EXECUTION_TIMEOUT_PREFIX = "実行がタイムアウトしました (";
    constexpr const char* RUNTIME_ERROR_EXECUTION_TIMEOUT_SUFFIX = "ms)。";
    constexpr const char* RUNTIME_ERROR_INVALID_ASSIGNMENT_TARGET = "無効な代入ターゲットです。";
    constexpr const char* RUNTIME_ERROR_CANNOT_CONVERT_STRING_TO_NUMBER_PREFIX = "文字列 '";
    constexpr const char* RUNTIME_ERROR_CANNOT_CONVERT_STRING_TO_NUMBER_SUFFIX = "' を数値に変換できません。";
    constexpr const char* RUNTIME_ERROR_CANNOT_CONVERT_STRING_TO_BINARY_PREFIX = "文字列 '";
    constexpr const char* RUNTIME_ERROR_CANNOT_CONVERT_STRING_TO_BINARY_SUFFIX = "' をバイナリオブジェクトに変換できません。'0x...' 形式である必要があります。";
    constexpr const char* RUNTIME_ERROR_LIST_INIT_WITH_LIST_ONLY = "リスト変数はリストでのみ初期化できます。";
    constexpr const char* RUNTIME_ERROR_SET_NODE_HANDLED_BY_ASSIGNMENT = "SetNode は AssignmentNode を介して処理されるべきです。";
    constexpr const char* RUNTIME_ERROR_ONLY_INSTANCES_HAVE_PROPERTIES_PREFIX = "インスタンスのみがプロパティを持つことができます。'";
    constexpr const char* RUNTIME_ERROR_ONLY_INSTANCES_HAVE_PROPERTIES_SUFFIX = "' を取得できません。";
    constexpr const char* RUNTIME_ERROR_ONLY_INSTANCES_CAN_SET_PROPERTIES = "インスタンスのみがプロパティを設定できます。";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_PROPERTY_PREFIX = "未定義のプロパティ '";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_PROPERTY_SUFFIX = "'。";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_FIELD_PREFIX = "未定義のフィールド '";
    constexpr const char* RUNTIME_ERROR_UNDEFINED_FIELD_SUFFIX = "' を設定できません。";
    constexpr const char* RUNTIME_ERROR_FIELD_TYPE_MISMATCH_PREFIX = "フィールド '";
    constexpr const char* RUNTIME_ERROR_FIELD_TYPE_MISMATCH_EXPECTED = "' の型が一致しません。期待される型 '";
    constexpr const char* RUNTIME_ERROR_FIELD_TYPE_MISMATCH_GOT = "' に対して、得られた型は '";
    constexpr const char* RUNTIME_ERROR_FIELD_TYPE_MISMATCH_SUFFIX = "' です。";
    constexpr const char* RUNTIME_ERROR_CAN_ONLY_CALL_FUNCTIONS = "関数またはメソッドのみ呼び出せます。呼び出し対象は '";
    constexpr const char* RUNTIME_ERROR_CAN_ONLY_CALL_FUNCTIONS_SUFFIX = "' でした。";

    // --- 関数とメソッド呼び出しのエラー ---
    constexpr const char* ERROR_ARG_COUNT_PREFIX_AT_LEAST = "' は少なくとも ";
    constexpr const char* ERROR_ARG_COUNT_PREFIX_EXACTLY = "' はちょうど ";
    constexpr const char* ERROR_ARG_COUNT_PREFIX_AT_MOST = "' は最大で ";
    constexpr const char* ERROR_ARG_COUNT_SUFFIX_BUT_GOT = " 個の引数を取りますが、";
    constexpr const char* ERROR_ARG_COUNT_SUFFIX_BUT_GOT_PLURAL = " 個の引数を取りますが、";
    constexpr const char* ERROR_ARG_COUNT_SUFFIX_SINGLE = " 個の引数を受け取りました。";
    constexpr const char* ERROR_ARG_COUNT_SUFFIX_PLURAL = " 個の引数を受け取りました。";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_PREFIX = "引数 ";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_IN_FUNCTION = " (関数 '";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_IN_METHOD = " (メソッド '";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_NAME = " ('";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_EXPECTED = "') の型が一致しません。期待される型 '";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_GOT = "' に対して、得られた型は '";
    constexpr const char* ERROR_ARG_TYPE_MISMATCH_SUFFIX = "' です。";
    constexpr const char* ERROR_SWAP_REQUIRES_TWO_VARS = "swap() は引数として2つの変数名を必要とします。";
    constexpr const char* ERROR_SWAP_ARGS_MUST_BE_VARS = "swap() の引数は変数名でなければなりません。";
    constexpr const char* ERROR_NEW_REQUIRES_CLASS = "new() の最初の引数はクラスでなければなりません。";


    // --- ネイティブ関数のエラー ---
    constexpr const char* NATIVE_ERROR_REQUIRES_ARGS_SUFFIX = "() は引数として ";
    constexpr const char* NATIVE_ERROR_REQUIRES_MIN_ARGS_SUFFIX = "() は少なくとも ";
    constexpr const char* NATIVE_ERROR_ARG_MUST_BE_NUMBER = "引数は数値でなければなりません。";
    constexpr const char* NATIVE_ERROR_ARG_MUST_BE_LIST = "引数はリストでなければなりません。";
    constexpr const char* NATIVE_ERROR_ARG_MUST_BE_STRING = "引数は文字列でなければなりません。";
    constexpr const char* NATIVE_ERROR_RT_ARGS = "rt() は1つまたは2つの引数を必要とします。";
    constexpr const char* NATIVE_ERROR_MIN_MAX_EMPTY = "min/max は少なくとも1つの引数を必要とします。";
    constexpr const char* NATIVE_ERROR_MIN_MAX_EMPTY_LIST = "空のリスト/引数セットから min/max を見つけることはできません。";
    constexpr const char* NATIVE_ERROR_MIN_MAX_UNCOMPARABLE = "min/max のすべての引数は比較可能な型（数値または文字列）でなければなりません。";
    constexpr const char* NATIVE_ERROR_TIMER_FN_NO_ARGS = "タイマー関数は引数を受け付けません。";
    constexpr const char* NATIVE_ERROR_LOG_POSITIVE = "log() の引数は正の数でなければなりません。";


    // --- パーサーのエラー ---
    constexpr const char* PARSE_ERROR_PREFIX = "[パースエラー] 行 ";
    constexpr const char* PARSE_ERROR_SUFFIX = "。\n";
    constexpr const char* PARSE_ERROR_UNEXPECTED_CHAR = "予期しない文字です。";
    constexpr const char* PARSE_ERROR_UNTERMINATED_STRING = "終端されていない文字列です。";
    constexpr const char* PARSE_ERROR_EXPECT_EXPRESSION = "式が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_VAR_NAME = "変数名が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_PARAM_TYPE = "関数の引数に型キーワード（dec, str, bin, list, any）が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_PARAM_NAME = "引数名が必要です。";
    constexpr const char* PARSE_ERROR_DEFAULT_VALUE_LITERAL = "デフォルトの引数値はリテラル（null, 数値, 文字列, 16進数, 空リスト）でなければなりません。";
    constexpr const char* PARSE_ERROR_UNSUPPORTED_DEFAULT_LIST = "現在、空でないリストをデフォルトの引数値としてサポートしていません。";
    constexpr const char* PARSE_ERROR_TOO_MANY_PARAMS = "引数は255個を超えることはできません。";
    constexpr const char* PARSE_ERROR_TOO_MANY_FIELDS = "クラスのフィールドは255個を超えることはできません。";
    constexpr const char* PARSE_ERROR_TOO_MANY_ARGS = "引数は255個を超えることはできません。";
    constexpr const char* PARSE_ERROR_EXPECT_FUNC_NAME = "関数名が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_METHOD_NAME = "メソッド名が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_LPAREN_AFTER_NAME = "名前の後に '(' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_RPAREN_AFTER_PARAMS = "引数の後に ')' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_DO_BEFORE_BODY = "関数本体の前に 'do' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_ENDDEF_AFTER_BODY = "関数本体の後に 'enddef' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_CLASS_NAME = "クラス名が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_RPAREN_AFTER_FIELDS = "フィールドの後に ')' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_CONTAINS_AFTER_CLASS_DEF = "クラス定義の後に 'contains' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_ENDINS_AFTER_CLASS_BODY = "クラス本体の後に 'endins' が必要です。";
    constexpr const char* PARSE_ERROR_ONLY_METHODS_IN_CLASS = "クラスの 'contains' ブロック内ではメソッド定義（def）のみが許可されています。";
    constexpr const char* PARSE_ERROR_EXPECT_THEN_AFTER_IF = "if 条件の後に 'then' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_ENDIF_AFTER_IF = "if 文の後に 'endif' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_DO_AFTER_WHILE = "while 条件の後に 'do' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_ENDWHILE_AFTER_WHILE = "while ループの後に 'endwhile' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_THEN_AFTER_AWAIT = "await 条件の後に 'then' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_ENDAWAIT_AFTER_AWAIT = "await 文の後に 'endawait' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_CATCH_AFTER_TRY = "'try' ブロックの後に 'catch' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_VAR_AFTER_CATCH = "'catch' の後に変数名が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_ENDTRY_AFTER_TRY = "try/catch/finally 構造の後に 'endtry' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_LPAREN_AFTER_SAY = "'say' には '(' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_RPAREN_AFTER_EXPR = "式の後に ')' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_LPAREN_AFTER_ASK = "'ask' には '(' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_RPAREN_AFTER_PROMPT = "プロンプトの後に ')' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_RBRACKET_AFTER_LIST = "リスト要素の後に ']' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_RBRACKET_AFTER_INDEX = "添字インデックスの後に ']' が必要です。";
    constexpr const char* PARSE_ERROR_EXPECT_PROP_NAME = "プロパティまたはメソッド名が必要です。";


    // --- デバッグメッセージ ---
    constexpr const char* DEBUG_ENV_DEFINE = "[デバッグ:環境] 環境 ";
    constexpr const char* DEBUG_ENV_IN_ENV = " で '";
    constexpr const char* DEBUG_ENV_AS = "' を ";
    constexpr const char* DEBUG_ENV_ASSIGN = "[デバッグ:環境] '";
    constexpr const char* DEBUG_ENV_VALUE = "' に代入中 = ";
    constexpr const char* DEBUG_ENV_ASSIGN_FAIL = "[デバッグ:環境] ";
    constexpr const char* DEBUG_ENV_TRY_ENCLOSING = " での代入に失敗、囲んでいる環境 ";
    constexpr const char* DEBUG_ENV_GET = "[デバッグ:環境] '";
    constexpr const char* DEBUG_ENV_FROM_ENV = "' を環境 ";
    constexpr const char* DEBUG_ENV_FOUND = "  '";
    constexpr const char* DEBUG_ENV_GET_FAIL = "  ";
    constexpr const char* DEBUG_PARSER_START = "[デバッグ:パーサー] パースを開始...";
    constexpr const char* DEBUG_PARSER_PARSING_DECL = "[デバッグ:パーサー] 宣言をパース中 (現在のトークン: ";
    constexpr const char* DEBUG_PARSER_PARSING_PARAM = "[デバッグ:パーサー] 引数をパース中...";
    constexpr const char* DEBUG_PARSER_PARSING_DEFAULT_VAL_FOR = "  '";
    constexpr const char* DEBUG_PARSER_PARSED_PARAM = "  パースされた引数: ";
    constexpr const char* DEBUG_PARSER_WITH_DEFAULT = " (デフォルト値付き)";
    constexpr const char* DEBUG_PARSER_PARSING_VAR_DECL = "[デバッグ:パーサー] 変数宣言をパース中...";
    constexpr const char* DEBUG_PARSER_PARSING_FUNC_DEF = "[デバッグ:パーサー] 関数定義をパース中...";
    constexpr const char* DEBUG_PARSER_PARSING_METHOD_DEF = "[デバッグ:パーサー] メソッド定義をパース中...";
    constexpr const char* DEBUG_PARSER_DONE_PARSING_FUNC = "  関数 '";
    constexpr const char* DEBUG_PARSER_DONE_PARSING_METHOD = "  メソッド '";
    constexpr const char* DEBUG_PARSER_PARSING_CLASS_DEF = "[デバッグ:パーサー] クラス定義をパース中...";
    constexpr const char* DEBUG_PARSER_DONE_PARSING_CLASS = "  クラス '";
    constexpr const char* DEBUG_PARSER_PARSING_ASSIGNMENT = "[デバッグ:パーサー] 代入式をパース中...";
    constexpr const char* DEBUG_PARSER_PARSING_CALL = "[デバッグ:パーサー] 関数呼び出しをパース中...";
    constexpr const char* DEBUG_PARSER_PARSING_SUBSCRIPT = "[デバッグ:パーサー] 添字アクセスをパース中...";
    constexpr const char* DEBUG_PARSER_PARSING_GET = "[デバッグ:パーサー] プロパティ/メソッドアクセスをパース中...";
    constexpr const char* DEBUG_INTERP_START = "[デバッグ:インタプリタ] ";
    constexpr const char* DEBUG_INTERP_STATEMENTS = " 個の文の解釈を開始します。";
    constexpr const char* DEBUG_INTERP_EXEC_TOP_LEVEL = "[デバッグ:インタプリタ] === トップレベル文 ";
    constexpr const char* DEBUG_INTERP_AT_LINE = " (行 ";
    constexpr const char* DEBUG_INTERP_END_EXEC_STMT = ") を実行中 ===";
    constexpr const char* DEBUG_INTERP_DONE = "[デバッグ:インタプリタ] 解釈が終了しました。";
    constexpr const char* DEBUG_INTERP_EXEC_STMT_TYPE = "[デバッグ:インタプリタ] 型 ";
    constexpr const char* DEBUG_INTERP_EVAL_EXPR_TYPE = "[デバッグ:インタプリタ] 型 ";
    constexpr const char* DEBUG_INTERP_BLOCK_ENTER = "[デバッグ:インタプリタ] ---> 新しいブロック/スコープに入ります。環境: ";
    constexpr const char* DEBUG_INTERP_BLOCK_PREVIOUS = " 前の環境: ";
    constexpr const char* DEBUG_INTERP_BLOCK_EXIT_EXCEPTION = "[デバッグ:インタプリタ] <--- 例外によりブロック/スコープを抜けます。環境を ";
    constexpr const char* DEBUG_INTERP_BLOCK_EXIT = "[デバッグ:インタプリタ] <--- ブロック/スコープを抜けます。環境を ";
    constexpr const char* DEBUG_EXEC_LITERAL_NODE = "[デバッグ:実行] LiteralNode を評価中。値: ";
    constexpr const char* DEBUG_EXEC_LIST_LITERAL_NODE = "[デバッグ:実行] ListLiteralNode を評価中 (";
    constexpr const char* DEBUG_EXEC_LIST_LITERAL_NODE_ELEMENTS = " 要素)。";
    constexpr const char* DEBUG_EXEC_VAR_NODE = "[デバッグ:実行] VariableNode '";
    constexpr const char* DEBUG_EXEC_ASSIGN_NODE = "[デバッグ:実行] AssignmentNode を実行中。代入する値: ";
    constexpr const char* DEBUG_EXEC_ASSIGN_TARGET_VAR = "  代入ターゲットは VariableNode: '";
    constexpr const char* DEBUG_EXEC_ASSIGN_TARGET_SUBSCRIPT = "  代入ターゲットは SubscriptNode です。";
    constexpr const char* DEBUG_EXEC_ASSIGN_TARGET_GET = "  代入ターゲットは GetNode: プロパティ '";
    constexpr const char* DEBUG_EXEC_VAR_DECL_NODE_INIT = "[デバッグ:実行] '";
    constexpr const char* DEBUG_EXEC_VAR_DECL_NODE_WITH_INIT = "' の VarDeclarationNode を実行中（初期化子あり）。";
    constexpr const char* DEBUG_EXEC_VAR_DECL_NODE_NO_INIT = "' の VarDeclarationNode を実行中（初期化子なし）。";
    constexpr const char* DEBUG_EXEC_VAR_DECL_DECLARED_TYPE = "  宣言された型: ";
    constexpr const char* DEBUG_EXEC_VAR_DECL_INITIAL_VALUE = "。初期値: ";
    constexpr const char* DEBUG_EXEC_VAR_DECL_FINAL_VALUE = "  型強制後の最終的な値: ";
    constexpr const char* DEBUG_EXEC_BINARY_OP = "[デバッグ:実行] BinaryOpNode を評価中（演算子: ";
    constexpr const char* DEBUG_EXEC_BINARY_OP_LEFT = "  左オペランド: ";
    constexpr const char* DEBUG_EXEC_BINARY_OP_RIGHT = ", 右オペランド: ";
    constexpr const char* DEBUG_EXEC_SUBSCRIPT_NODE = "[デバッグ:実行] SubscriptNode を評価中。";
    constexpr const char* DEBUG_EXEC_SUBSCRIPT_NODE_OBJ = "  オブジェクト: ";
    constexpr const char* DEBUG_EXEC_SUBSCRIPT_NODE_IDX = ", インデックス: ";
    constexpr const char* DEBUG_EXEC_IF_NODE = "[デバッグ:実行] IfStatementNode を実行中。条件を評価しています...";
    constexpr const char* DEBUG_EXEC_IF_CONDITION_TRUE = "  条件は真です";
    constexpr const char* DEBUG_EXEC_IF_CONDITION_FALSE = "  条件は偽です";
    constexpr const char* DEBUG_EXEC_IF_CONDITION_VALUE = " (";
    constexpr const char* DEBUG_EXEC_IF_THEN = "  'then' ブランチを実行中。";
    constexpr const char* DEBUG_EXEC_IF_ELSE = "  'else' ブランチを実行中。";
    constexpr const char* DEBUG_EXEC_WHILE_NODE = "[デバッグ:実行] WhileStatementNode を実行中。";
    constexpr const char* DEBUG_EXEC_WHILE_CONDITION_TRUE = "  While ループの条件は真です";
    constexpr const char* DEBUG_EXEC_WHILE_CONDITION_FALSE = "  While ループの条件は偽です";
    constexpr const char* DEBUG_EXEC_WHILE_FINALLY = "  while ループの 'finally' ブランチを実行中。";
    constexpr const char* DEBUG_EXEC_AWAIT_NODE = "[デバッグ:実行] AwaitStatementNode を実行中。条件を待機しています...";
    constexpr const char* DEBUG_EXEC_AWAIT_SATISFIED = "  Await 条件が満たされました。'then' ブランチを実行中。";
    constexpr const char* DEBUG_EXEC_SAY_NODE = "[デバッグ:実行] SayNode を実行中。";
    constexpr const char* DEBUG_EXEC_SAY_VALUE = "  出力する値: ";
    constexpr const char* DEBUG_EXEC_FUNC_DEF_NODE = "[デバッグ:実行] '";
    constexpr const char* DEBUG_EXEC_CLASS_DEF_NODE = "[デバッグ:実行] クラス '";
    constexpr const char* DEBUG_EXEC_CLASS_DEF_PROCESSING_METHOD = "  メソッド '";
    constexpr const char* DEBUG_EXEC_GET_NODE = "[デバッグ:実行] プロパティ '";
    constexpr const char* DEBUG_EXEC_GET_NODE_OBJECT_EVAL = "  オブジェクトの評価結果: ";
    constexpr const char* DEBUG_EXEC_CALL_NODE = "[デバッグ:実行] CallNode を実行中（行 ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_EVAL_CALLEE = "）。呼び出し対象を評価中...";
    constexpr const char* DEBUG_EXEC_CALL_NODE_CALLEE_EVAL = "  呼び出し対象の評価結果: ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_EVAL_ARGS = "  ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_ARGS = " 個の引数を評価中...";
    constexpr const char* DEBUG_EXEC_CALL_NODE_NATIVE = "  ネイティブ関数 '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_USER = "  ユーザー関数 '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_BINDING_ARGS = "    ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_ARGS_TO = " 個の引数を ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_PARAMS = " 個の仮引数にバインド中（";
    constexpr const char* DEBUG_EXEC_CALL_NODE_REQUIRED = " 個が必要）。";
    constexpr const char* DEBUG_EXEC_CALL_NODE_BINDING_PARAM = "      仮引数 '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_TO_ARG = "' を実引数 ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_PUSH_STACK = "    '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_TO_STACK = "' をコールスタックにプッシュ中。";
    constexpr const char* DEBUG_EXEC_CALL_NODE_POP_STACK = "    '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_FROM_STACK = "' をコールスタックからポップ中。戻り値: ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_BOUND_METHOD = "  バインドされたメソッド '";
    constexpr const char* DEBUG_EXEC_CALL_NODE_ON_INSTANCE = "' をインスタンス ";
    constexpr const char* DEBUG_EXEC_CALL_NODE_DEFINE_THIS = "    メソッドスコープで 'this' を定義中。";
    constexpr const char* DEBUG_EXEC_RETURN_NODE = "[デバッグ:実行] ReturnNode を実行中。ReturnValueException をスローします。値: ";
    constexpr const char* DEBUG_EXEC_RAISE_NODE = "[デバッグ:実行] RaiseNode を実行中。PyRiteRaiseException をスローします。ペイロード: ";
    constexpr const char* DEBUG_EXEC_TRY_NODE = "[デバッグ:実行] TryCatchNode を実行中。'try' ブロックに入ります。";
    constexpr const char* DEBUG_EXEC_TRY_CAUGHT_PYRITE = "  'try' ブロックで PyRiteRaiseException をキャッチしました。ペイロード: ";
    constexpr const char* DEBUG_EXEC_TRY_EXEC_CATCH = "。'catch' ブロックを実行中。";
    constexpr const char* DEBUG_EXEC_TRY_CAUGHT_RUNTIME = "  'try' ブロックで RuntimeError をキャッチしました: ";
    constexpr const char* DEBUG_EXEC_TRY_CAUGHT_UNEXPECTED = "  'catch' ブロックで予期しない例外をキャッチしました。'finally' の後に再スローされます。";
    constexpr const char* DEBUG_EXEC_TRY_EXEC_FINALLY = "  'finally' ブロックを実行中。";
    constexpr const char* DEBUG_EXEC_TRY_RETHROWING = "  'catch' ブロックから例外を再スロー中。";
    constexpr const char* DEBUG_EXEC_TRY_DONE = "  TryCatchNode の実行が完了しました。";
    constexpr const char* DEBUG_EXEC_EXPR_STMT_NODE = "[デバッグ:実行] ExpressionStatementNode を実行中。";
    constexpr const char* DEBUG_INSTANCE_CREATING = "[デバッグ:インスタンス] '";
    constexpr const char* DEBUG_INSTANCE_NEW_ENV = "' のインスタンスを作成中。新しい環境を作成します。囲んでいる環境: ";
    constexpr const char* DEBUG_INSTANCE_INIT_FIELD = "  フィールド '";
    constexpr const char* DEBUG_INSTANCE_WITH_DEFAULT = "' をデフォルト値 ";
    constexpr const char* DEBUG_INSTANCE_GET_PROP = "[デバッグ:インスタンス] プロパティ '";
    constexpr const char* DEBUG_INSTANCE_FROM = "' をインスタンス '";
    constexpr const char* DEBUG_INSTANCE_CHECK_FIELDS = "' から取得中。  インスタンスのフィールドを確認中...";
    constexpr const char* DEBUG_INSTANCE_PROP_NOT_IN_FIELDS = "  プロパティ '";
    constexpr const char* DEBUG_INSTANCE_CHECK_METHODS = "' はフィールドにありません。クラスのメソッドを確認中...";
    constexpr const char* DEBUG_INSTANCE_FOUND_METHOD = "  メソッド '";
    constexpr const char* DEBUG_INSTANCE_CREATING_BOUND_METHOD = "' が見つかりました。バインドされたメソッドを作成中。";
    constexpr const char* DEBUG_INSTANCE_SET_PROP = "[デバッグ:インスタンス] プロパティ '";
    constexpr const char* DEBUG_INSTANCE_FOR = "' をインスタンス '";
    constexpr const char* DEBUG_INSTANCE_TO_VALUE = "' に設定中。値 ";
    constexpr const char* DEBUG_INSTANCE_FOUND_FIELD = "  フィールド '";
    constexpr const char* DEBUG_INSTANCE_TYPE_CHECKING = "' が見つかりました。型チェック中... 期待される型: ";
    constexpr const char* DEBUG_INSTANCE_TYPE_CHECK_OK = "  型チェックに合格しました。フィールド値を設定中。";

    // --- REPL と Main ---
    constexpr const char* REPL_WELCOME_BANNER_1 = "PyRite インタプリタ ";
    constexpr const char* REPL_WELCOME_BANNER_DEBUG = " [デバッグ]";
    constexpr const char* REPL_WELCOME_BANNER_2 = ".\n";
    constexpr const char* REPL_WELCOME_BANNER_3 = "'run()' でバッファされたコードを実行、'halt()' で終了、'about()' でバージョン情報を表示します。\n";
    constexpr const char* REPL_HALTED = "インタプリタが停止しました。";
    constexpr const char* REPL_NO_CODE_TO_RUN = "実行するコードがありません。";
    constexpr const char* REPL_TICK_ARG_ERROR = "[ランタイムエラー] run() の 'tick' 引数はブール値（0/1, false/true）でなければなりません。";
    constexpr const char* REPL_LIMIT_ARG_ERROR_LITERAL = "[ランタイムエラー] run() の 'limit' 引数は数値リテラルでなければなりません。";
    constexpr const char* REPL_LIMIT_ARG_ERROR_INVALID = "[ランタイムエラー] run() の 'limit' 引数が無効です。";
    constexpr const char* REPL_EXECUTION_TIME_PREFIX = "コード実行時間: ";
    constexpr const char* REPL_EXECUTION_TIME_SUFFIX = "ms。";
    constexpr const char* ABOUT_HEADER_FOOTER = "----------------------------------------\n";
    constexpr const char* ABOUT_LINE_1 = " PyRite 言語インタプリタ ";
    constexpr const char* ABOUT_LINE_2 = "\n (c) 2024-2025. DarkstarXD. All Rights Reserved.\n";
    constexpr const char* ABOUT_LINE_3 = " 魔法のようにシンプルなプログラミング言語?!\n";
    constexpr const char* MAIN_USAGE_ERROR = "使用法: ";
    constexpr const char* MAIN_USAGE_ERROR_SCRIPT = " [script.src]";
    constexpr const char* MAIN_FILE_OPEN_ERROR = "エラー: ファイル '";

    // --- コンパイル ---
    constexpr const char* COMPILE_SYNTAX_ERROR = "構文エラー: 呼び出しに '()' がありません。";
    constexpr const char* COMPILE_ARG_SYNTAX_ERROR = "構文エラー: 引数は key=value 形式でなければなりません。";
}

#endif // MESSAGES_HPP
