#pragma once
#include <string>

enum class Msg {
    // --- operators ---
    ADD_TYPE, SUB_TYPE, MUL_TYPE, DIV_TYPE, POW_TYPE, MOD_TYPE, CMP_TYPE,
    NOT_SUBSCR, NO_ITEM_SET, LN_REPEAT_INT, LN_IDX_NUM, LN_IDX_OOB, LN_IDX_INV,
    HEX_PREFIX,

    // --- runtime ---
    RUNTIME_PREFIX, UNDEFINED_VAR, UNCAUGHT_EX, STACK_TRACE, STACK_ENTRY,
    TIMEOUT, INVALID_ASSIGN, STR_TO_NUM, STR_TO_BIN, LN_INIT_LN,
    SET_NODE_ERR, NO_PROP, NO_SET_PROP, UNDEF_PROP, UNDEF_FIELD,
    FIELD_TYPE, CALL_ONLY,

    // --- args ---
    ARGS_AT_LEAST, ARGS_EXACT, ARGS_AT_MOST, ARGS_GOT,
    ARG_TYPE, SWAP_TWO_VARS, SWAP_VARS, NEW_CLASS,

    // --- native fns ---
    NATIVE_ARGS, NATIVE_MIN_ARGS, NATIVE_NUM, NATIVE_LN, NATIVE_STR,
    NATIVE_RT, NATIVE_MINMAX_EMPTY, NATIVE_MINMAX_LIST, NATIVE_MINMAX_CMP,
    NATIVE_TIMER, NATIVE_LOG_POS,

    // --- parser ---
    PARSE_PREFIX, PARSE_UNEXPECTED, PARSE_UNTERM_STR, PARSE_EXPR,
    PARSE_VAR_NAME, PARSE_PARAM_TYPE, PARSE_PARAM_NAME, PARSE_DEFAULT_VAL,
    PARSE_DEFAULT_LN, PARSE_TOO_MANY_PARAMS, PARSE_TOO_MANY_FIELDS,
    PARSE_TOO_MANY_ARGS, PARSE_FUNC_NAME, PARSE_METHOD_NAME,
    PARSE_LPAREN_NAME, PARSE_RPAREN_PARAMS, PARSE_DO_BODY,
    PARSE_CLASS_NAME, PARSE_RPAREN_FIELDS, PARSE_CONTAINS,
    PARSE_ENDINS, PARSE_ONLY_METHODS, PARSE_THEN_IF, PARSE_ENDIF,
    PARSE_DO_WHILE, PARSE_ENDWHILE, PARSE_THEN_AWAIT, PARSE_ENDAWAIT,
    PARSE_CATCH_TRY, PARSE_VAR_CATCH, PARSE_ENDTRY,
    PARSE_LPAREN_SAY, PARSE_RPAREN_EXPR, PARSE_LPAREN_ASK, PARSE_RPAREN_PROMPT,
    PARSE_RBRACKET_LN, PARSE_RBRACKET_IDX, PARSE_PROP_NAME,
    PARSE_STRUCT_NAME, PARSE_RPAREN_STRUCT,

    // --- I/O (not errors) ---
    REPL_WELCOME1, REPL_DEBUG, REPL_WELCOME3, REPL_HALTED, REPL_NO_CODE,
    REPL_TICK, REPL_LIMIT_LIT, REPL_LIMIT_INV, REPL_TIME,
    ABOUT_HEADER, ABOUT_LINE1, ABOUT_LINE2, ABOUT_LINE3,
    MAIN_USAGE, MAIN_SCRIPT, MAIN_OPEN,
    REPL_HELP_NOT_FOUND, REPL_HELP_SUGGESTION,

    // --- main help text ---
    MAIN_HELP_HEADER,
    MAIN_HELP_VM, MAIN_HELP_AST, MAIN_HELP_DUMP,
    MAIN_HELP_EMIT_BC, MAIN_HELP_EMIT_AST,
    MAIN_HELP_SAVE_BC, MAIN_HELP_SAVE_AST,
    MAIN_HELP_HELP,
    MAIN_HELP_FORMATS, MAIN_HELP_PR, MAIN_HELP_PRC, MAIN_HELP_PRT,

    // --- main I/O errors ---
    MAIN_LOAD_ERR, MAIN_COMPILE_ERR, MAIN_OPT_NEED_ARG,
    MAIN_UNKNOWN_OPT, MAIN_HELP_HINT, MAIN_SAVE_NEED_SRC,
    MAIN_SAVE_OK_BC, MAIN_SAVE_OK_AST,
    MAIN_SAVE_ERR_BC, MAIN_SAVE_ERR_AST,

    // --- slice ---
    SLICE_TOO_LARGE, SLICE_MUST_NUM, SLICE_STEP_ZERO, SLICE_UNSUPPORTED,
    SLICE_ASSIGN, SLICE_LN_ONLY,

    // --- dim ---
    DIM_KEY_MISS, DIM_KEY_TYPE,

    // --- loop ---
    LOOP_MUST_NUM, LOOP_TOO_LARGE,

    // --- dim init ---
    DIM_INIT_DIM,
};

const char* msg(Msg id);

// fmt functions: replace dynamic content
std::string fmt(Msg id, const std::string& arg);
std::string fmt2(Msg id, const std::string& a1, const std::string& a2);
std::string fmt3(Msg id, const std::string& a1, const std::string& a2, const std::string& a3);
std::string fmt_int(Msg id, long long n);
